### ISSUE TITLE
Schematics not actually attached

### ISSUE THREAD

**Issue by Ampt** [keebio/keebio-docs#16]
I believe that in https://github.com/keebio/keebio-docs/commit/04fa544f6fe7a4895934ac96620ab0b7f3794aa8 you meant to include the schematics for the BFO-9000 and Nyquist, but the schematics folder never made it into the commit. Could you either add the schematics folder, or, if you don't plan on doing that, remove the dead links from `schematics.md`

Thank you!

**Comment by nooges** [comment]
Fixed in https://github.com/keebio/keebio-docs/commit/77bad60355c435f0318f7cf6f7cb11e1ab88df27, had to remove `*.pdf` in `.gitignore`
