### ISSUE TITLE
Note that Iris can't use I2C and underglow concurrently

### ISSUE THREAD

**Issue by jibreil** [keebio/keebio-docs#25]
I just built my iris and it took me a while to figure out why my qmk firmware that was compiled with I2C enabled wasn't working correctly and that was because I was using underglow as well.

Maybe you could make a note in the build guide that you can only use I2C **or** underglow and not both at the same time.

**Comment by nooges** [comment]
It can now using the `RGBLED_SPLIT` option https://docs.qmk.fm/#/config_options?id=rgb-light-configuration
