### ISSUE TITLE
Build guides for Viterbi 2.0

### ISSUE THREAD

**Issue by BurnzZ** [keebio/keebio-docs#31]
Good Day!

We've recently bought PCBs and have noticed that they were marked as Viterbi 2.0. However, we couldn't find any documentation in the docs.

Is it more or less the same as with the Nyquist's?

Thanks!

**Comment by nooges** [comment]
Main difference with Viterbi 2.0 is that both the controllers face the same direction, similar to the Quefrency.

**Comment by nooges** [comment]
Partially resolved with https://github.com/keebio/keebio-docs/commit/6a25c0850c044ef74d0610cf97c66a2cbaff465b
