### ISSUE TITLE
Schematics for Viterbi 2.0

### ISSUE THREAD

**Issue by BurnzZ** [keebio/keebio-docs#35]
I noticed that **Nyquist** already has its **Rev. 2** schematic uploaded in the page: https://docs.keeb.io/schematics/

May I ask if we have a timeline for when the **Viterbi 2.0** schematic be uploaded?

I'm currently debugging why some of my rows and columns aren't working and a schematic would really be helpful.

Cheers!

**Comment by BurnzZ** [comment]
Hi @nooges, could I have a gentle bump on this one?

My left-side of the **Viterbi 2.0 PCB** isn't communicating with the right-side, so far I think it's because of the short circuit as shown in the image below, where the **GND** isn't connected to anything at all while **D2** is connected somehow to **VCC**.

BTW, both sides work when connected via USB, but I still want to fix this problem since I want to use them via TRRS.

Having the **Viterbi 2.0 Schematic** would tremendously helpful in finding the short.

Cheers!

![viterbi-2 0-short](https://user-images.githubusercontent.com/3449761/58747936-71c8d180-84a4-11e9-89be-8721ed9064ff.png)

**Comment by nooges** [comment]
Added in https://github.com/keebio/keebio-docs/commit/0d9feee64f0e9b525c97c5c10fa90ccfd7f22a9d
