### ISSUE TITLE
Iris Kaihl Low Profile Rev 2 has pictures for regular Iris PCB

### ISSUE THREAD

**Issue by airvin** [keebio/keebio-docs#46]
The regular Iris PCB has the opposite vertical orientation of the diodes to the low profile version. The low profile build guide should show pictures of the low profile PCB with the black line of the diodes pointing up. It should also remove the line "On the bottom side of the PCB, insert diodes with the black line towards the bottom " or at least fix that to say "towards the top".

**Comment by nooges** [comment]
Since the PCB is out of stock, and I no have any of them, I won't be able to do pictures for them.
