### ISSUE TITLE
Suggestion: Use Hint Style to highlight notes or warnings

### ISSUE THREAD

**Issue by youngheart80** [keebio/keebio-docs#7]
First up, the new docs are looking really good. Nice to see them coming together.

One I was going to suggest was using the hint style formatting similar to the QMK docs (also hosted in Gitbook) for the warnings and notes about MOSFET pads, etc. in the Iris build. 

Example: QMK [Getting Started](https://docs.qmk.fm/complete-newbs-guide/getting-started) page uses this syntax:
`{% hint style='info' %} Not sure which text editor to use? Laurence Bradford wrote a great introduction to the subject. {% endhint %}`

As I didn't have access via Gitbook, I didn't know how to go about testing it to see if it would work, or if that is something custom on the QMK folks have done above and beyond Gitbook.

Thoughts?

**Comment by youngheart80** [comment]
Just found the info about hints in the QMK Documentation Best Practices. https://docs.qmk.fm/reference/documentation-best-practices

I'll try it out and see how it goes.

**Comment by nooges** [comment]
Yeah, that seems like a good starting point to use that guide. I think QMK is just using the stock Gitbook setup.

**Comment by youngheart80** [comment]
Okay, I'll make some time this weekend and see about moving those notes over to the hint style.
