### ISSUE TITLE
Re programming board note for `quefrency-rev2-sinc-build-guide`.

### ISSUE THREAD

**Issue by itsbenweeks** [keebio/keebio-docs#88]
I can't seem to find the section linked at https://docs.keeb.io/quefrency-rev2-sinc-build-guide/flashing-firmware/ but would like to know how to reprogram this board.

**Comment by nooges** [comment]
It's here: https://docs.keeb.io/flashing-firmware

**Comment by itsbenweeks** [comment]
Thanks!
