### ISSUE TITLE
Elite-Pi with KMK

### ISSUE THREAD

**Issue by F1hone** [keebio/keebio-docs#89]
How should Elite-Pi use KMK?
 I didn't find any support for Elite-Pi on circuitpython,
 and there is no part about KMK in Elite-Pi's firmware tutorial.

**Comment by AstraLuma** [comment]
I started a PR for board support https://github.com/adafruit/circuitpython/pull/7141

Still need to build a pin mapping.

**Comment by AstraLuma** [comment]
> The Elite-Pi is equivalent to the Raspberry Pi Pico, so you can use the CircuitPython release for that: https://circuitpython.org/board/raspberry_pi_pico/

Nearly. The Pico doesn't expose GPIO29 like the Elite-Pi does, and it's unclear if Maple Computing kept the VBUS sense feature of GPIO24.

**Comment by nooges** [comment]
There is official support for it now: https://circuitpython.org/board/maple_elite_pi/
