### ISSUE TITLE
No Keymap for Convolution 65XT

### ISSUE THREAD

**Issue by JackWitherell** [keebio/keebio-docs#96]
The selling page for this board:
https://keeb.io/products/convolution-65xt-keyboard
![image](https://user-images.githubusercontent.com/4626546/228408802-f8885600-9011-41b3-b47a-9d9f474e1218.png)

Lists this page from the docs as a resource to find the Keymap
https://docs.keeb.io/default-keymaps
![image](https://user-images.githubusercontent.com/4626546/228408903-5f49180b-ae7a-4c21-9e8d-622628aea5b2.png)

Yet that board isn't listed. Where's the Keymap for the Convolution 65XT?

**Comment by nooges** [comment]
For now, the default keymap can be viewed by opening up [VIA](https://usevia.app) and connecting the keyboard to that or by going to https://config.qmk.fm/#/keebio/convolution/rev1/LAYOUT_65xt

**Comment by nooges** [comment]
Added with 32d03fba720c538a05a01b4feafa16dccd600e1e now
